<table align="center" width=100%>
    <tr>
        <td width="15%">
            <img src="homework.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> TakeHome <br> (Session 3) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

### Let's begin with some hands-on practice exercises

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create an array of integers from 20 to 2 with a step of -2
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [1]:
# Write your code here
import numpy as np

array1 = np.arange(start = 20, stop = 2, step = -2)

print(array1)

[20 18 16 14 12 10  8  6  4]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Find the minimum value along the row
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

#### Create a 2D Numpy array from list of lists

```
arr2D = np.array([
                     [110, 102, 183],
                     [140, 175, 106],
                     [170, 195, 117],
                     [192, 140, 195]
                     ])
```

In [2]:
# Write your code here
arr2D = np.array([[110, 102, 183],[140, 175, 106],[170, 195, 117],[192, 140, 195]])

print(arr2D)

[[110 102 183]
 [140 175 106]
 [170 195 117]
 [192 140 195]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Replace all odd numbers in array with -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [7]:
# Write your code here
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
i = 0
while i < arr.size:
    if arr[i] %2 != 0:
        arr[i] = -2
    i = i + 1

print(arr)

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Replace all odd numbers in arr with -2 without changing original array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [35]:
# Write your code here
import numpy as np

arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

new_list = []


for item in arr:
    if item % 2 !=0:
       new_list.append(-2)
    else:
        new_list.append(item)

new_array = np.array(new_list)
print("Old Array:",arr)
print("New Array:",new_array)

Old Array: [ 0 31 42 43 34 45 26 27 38 94 65 78 76]
New Array: [ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Stack two arrays vertically
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.arange(10).reshape(2,-1)<br>
array2 = np.repeat(1, 10).reshape(2,-1)

In [ ]:
# Write your code here

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Get commom elements between two arrays
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.array([11,12,13,22,23,44,43,24,45,36])<br>
array2 = np.array([17,22,13,22,47,34,39,44,29,28])

In [37]:
# Write your code here

array1 = np.array([11,12,13,22,23,44,43,24,45,36])
array2 = np.array([17,22,13,22,47,34,39,44,29,28])

common_list = []

for i in array1:
    for j in array2:
        if i == j  and i not in common_list:
            common_list.append(i)

common_array = np.array(common_list)

print(common_array)
            

[13 22 44]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. From array1 remove all items present in array2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.array([1,2,3,4,5])<br>
array2 = np.array([5,6,7,8,9])

In [8]:
# Write your code here
import numpy as np 

array1 = np.array([1,2,3,4,5])
array2 = np.array([5,6,7,8,9])

for i in array1:
    print("i=",i)
    for j in array2:
        print("j=",j)
        if i == j:
            print("matched")
            index = np.argwhere(i==j)
            print("Index:", index)
            array1 = np.delete(i, index)

print(array1)

i= 1
j= 5
j= 6
j= 7
j= 8
j= 9
i= 2
j= 5
j= 6
j= 7
j= 8
j= 9
i= 3
j= 5
j= 6
j= 7
j= 8
j= 9
i= 4
j= 5
j= 6
j= 7
j= 8
j= 9
i= 5
j= 5
matched
Index: []
j= 6
j= 7
j= 8
j= 9
5


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Get the positions where elements of two array match
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.array([1,2,3,2,3,4,3,4,5,6])<br>
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [58]:
# Write your code here

array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

i = j = 0

while i < array1.size:
    while j < array2.size:
        if array1[i] == array2[j]:
            print("Matching positions are", i, j)
        j = j + 1
        i = i + 1    

Matching positions are 1 1
Matching positions are 3 3
Matching positions are 5 5
Matching positions are 7 7


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Reverse the columns of a 2D array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.arange(9).reshape(3,3)<br>


In [ ]:
# Write your code here

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Swap rows 1 and 2 in the given array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.arange(9).reshape(3,3)<br>

In [ ]:
# Write your code here