<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Session 3) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[For Loop](#loop)**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

list1 = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [1]:
# type your code here

import numpy as np

list1 = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
array1 = np.array(list1)

print(array1)

[3.04 1.65 5.76 1.66 1.54 4.69 2.68]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [2]:
# type your code here

weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

array_weights = np.array(weights)

print(weights)

for i in weights:
    if i > 68:
        print(i)

[74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
74.2
85
74
70.5
86
82


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [51]:
# type your code here
np.random.seed(42)

array_seed = np.random.randint(20, 41, size=(10))
print("Seed Array:",array_seed)



Seed Array: [26 39 34 30 27 40 26 38 30 30]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [55]:
# type your code here

array = np.arange(start=51, stop=100, step=2)
print("Array:",array)

Array: [51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5.Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

array1 = [10, 30, 50, 60, 90]

array2 = [50, 20, 80, 125, 10, 70]

In [64]:
# type your code here

array1 = [10, 30, 50, 60, 90]
array1 = np.array(array1)

array2 = [50, 20, 80, 125, 10, 70]
array2 = np.array(array2)

print(array1)
print(array2)

for i in array1:
    if i in array2:
        print("Common element:",i)
        

[10 30 50 60 90]
[ 50  20  80 125  10  70]
Common element: 10
Common element: 50


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

list of weights (in kg)
weights = [57, 69, 54, 65 ,71, 62, 56]

list of heights (in m)<br>
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [62]:
# type your code here

#list of weights (in kg)
weights = [57, 69, 54, 65 ,71, 62, 56]
weights_array = np.array(weights)

#list of heights (in m)
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 
heights_array = np.array(heights)

bmi = weights_array / (heights_array ** 2)

print(bmi)





22.54657648036074
[22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [68]:
# type your code here
from numpy import ones
identity5x5 = np.eye(5, dtype=int)
print(identity5x5)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [70]:
# type your code here

M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
matrix = np.array(M)
print("Original Matrix:",matrix)

transpose_matrix = np.transpose(matrix)

print("Transpose Matrix:",transpose_matrix)

Original Matrix: [[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]]
Transpose Matrix: [[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="loop"> </a>
## 3. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to perform one-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]

In [73]:
# type your code here

L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]

one_one_map_list = list(zip(L1, L2))

print(one_one_map_list)

[(45, 21), (67, 52), (56, 64), (71, 10), (54, 49), (62, 74), (56, 26)]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to change values in the array with the corresponding square root values</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**
    
num = [49, 81, 64, 25, 121, 1]

**The output should be:**

num = [7, 9, 8, 5, 11, 1]

In [78]:
# type your code here

num = [49, 81, 64, 25, 121, 1]
num = np.array(num)

for i in num:
    i = int(i ** (1/2))
print(num)    

[ 49  81  64  25 121   1]
